// src/terrain.js

export const TILE_TYPE = {
  FLOOR: ".",
  WALL: "#",
  CACTUS: "Ψ",
  CACTUS_2: "☨",
  CACTUS_3: "‡",
  SHRUB: "*",
  SHRUB_2: "⁂",
  SHRUB_3: "%",
  SETTLEMENT_WALL: "=",
  DOOR: "+",
  PLACARD: "팻",
  FIRE_PIT_INACTIVE: "~",
  ROCK: "o",
  WATER_TROUGH: "U",
  CRATE: "⌧",
  BARREL: "◎",
  FENCE_H: "─",
  FENCE_V: "│",
  FENCE_POST: "┼",
};

const duckableDescription =
  "You can duck behind it for cover. You can aim and shot from behind cover.";

export const terrainInfo = {
  [TILE_TYPE.FLOOR]: {
    name: "sand",
    isPassable: true,
    isTransparent: true,
    isBulletPassable: true,
    color: "#D2B48C",
    darkColor: "#423e37",
  },
  [TILE_TYPE.WALL]: {
    name: "a sturdy wall",
    isPassable: false,
    isTransparent: false,
    isBulletPassable: false,
    color: "#8B4513",
  },
  [TILE_TYPE.CACTUS]: {
    name: "a saguaro cactus",
    description: `A tall cactus. ${duckableDescription}`,
    isPassable: false,
    isTransparent: true,
    isBulletPassable: false,
    health: 15,
    color: "#2E8B57",
  },
  [TILE_TYPE.CACTUS_2]: {
    name: "a prickly pear cactus",
    description: duckableDescription,
    isPassable: false,
    isTransparent: true,
    isBulletPassable: false,
    health: 15,
    color: "#2E8B57",
  },
  [TILE_TYPE.CACTUS_3]: {
    name: "a barrel cactus",
    description: duckableDescription,
    isPassable: false,
    isTransparent: true,
    isBulletPassable: false,
    health: 15,
    color: "#2E8B57",
  },
  [TILE_TYPE.SHRUB]: {
    name: "a tough shrub",
    isPassable: true,
    isTransparent: true,
    isBulletPassable: true,
    color: "#556B2F",
  },
  [TILE_TYPE.SHRUB_2]: {
    name: "a sagebrush",
    isPassable: true,
    isTransparent: true,
    isBulletPassable: true,
    color: "#6B8E23",
  },
  [TILE_TYPE.SHRUB_3]: {
    name: "a creosote bush",
    isPassable: true,
    isTransparent: true,
    isBulletPassable: true,
    color: "#8FBC8F",
  },
  [TILE_TYPE.SETTLEMENT_WALL]: {
    name: "a settlement wall",
    isPassable: false,
    isTransparent: false,
    isBulletPassable: false,
    color: "#A9A9A9",
  },
  [TILE_TYPE.DOOR]: {
    name: "a wooden door",
    isPassable: true,
    isTransparent: false, // Blocks line of sight
    isBulletPassable: true, // But not bullets
    color: "#A0522D",
  },
  [TILE_TYPE.PLACARD]: {
    name: "a wooden sign",
    isPassable: false,
    isTransparent: true,
    isBulletPassable: true,
    color: "#8B4513",
  },
  [TILE_TYPE.FIRE_PIT_INACTIVE]: {
    name: "an inactive fire pit",
    description: "You can cook beans on it",
    isPassable: true,
    isTransparent: true,
    isBulletPassable: true,
    color: "#706f6f",
  },
  [TILE_TYPE.ROCK]: {
    name: "a rock",
    description: duckableDescription,
    isPassable: true,
    isTransparent: true,
    isBulletPassable: true,
    color: "#8d8d8d",
  },
  [TILE_TYPE.WATER_TROUGH]: {
    name: "a water trough",
    description: duckableDescription,
    isPassable: true,
    isTransparent: true,
    isBulletPassable: true,
    health: 30,
    color: "#4682B4",
  },
  [TILE_TYPE.CRATE]: {
    name: "a wooden crate",
    description: duckableDescription,
    isPassable: true,
    isTransparent: true,
    isBulletPassable: true,
    health: 4,
    color: "#8B4513",
  },
  [TILE_TYPE.BARREL]: {
    name: "a barrel",
    description: duckableDescription,
    isPassable: true,
    isTransparent: true,
    isBulletPassable: true,
    health: 8,
    color: "#8B4513",
  },
  [TILE_TYPE.FENCE_H]: {
    name: "a wooden fence",
    isPassable: true,
    isTransparent: true,
    isBulletPassable: true,
    color: "#A0522D",
  },
  [TILE_TYPE.FENCE_V]: {
    name: "a wooden fence",
    isPassable: true,
    isTransparent: true,
    isBulletPassable: true,
    color: "#A0522D",
  },
  [TILE_TYPE.FENCE_POST]: {
    name: "a fence post",
    isPassable: true,
    isTransparent: true,
    isBulletPassable: true,
    color: "#A0522D",
  },
};
